export const players = [
    {
        id: 1,
        name: "Cristiano Ronaldo",
        team: "Juventus",
        country: "Portugal",
        age: 35,
        position: "Delantero",
    },
    {
        id: 2,
        name: "Lionel Messi",
        team: "Barcelona",
        country: "Argentina",
        age: 33,
        position: "Delantero",
    },
    {
        id: 3,
        name: "Neymar Jr",
        team: "PSG",
        country: "Brasil",
        age: 28,
        position: "Delantero",
    },
    {
        id: 4,
        name: "Kylian Mbappé",
        team: "PSG",
        country: "Francia",
        age: 21,
        position: "Delantero",
    },
    {
        id: 5,
        name: "Sergio Ramos",
        team: "Real Madrid",
        country: "España",
        age: 34,
        position: "Defensa",
    },
    {
        id: 6,
        name: "Robert Lewandowski",
        team: "Bayern Munich",
        country: "Polonia",
        age: 32,
        position: "Delantero",
    },
    {
        id: 7,
        name: "Kevin De Bruyne",
        team: "Manchester City",
        country: "Belgica",
        age: 29,
        position: "Mediocampista",
    }
]
