export const players = [
    {
        id: 1,
        name: "Cristiano Ronaldo",
        team: "Juventus",
        country: "Portugal",
        age: 35,
        image:"https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NzQ0NjUxMDk1NDE4NDk4/cristiano-ronaldo-festeja.jpg",
        position: "Delantero",
    },
    {
        id: 2,
        name: "Lionel Messi",
        team: "Barcelona",
        country: "Argentina",
        age: 33,
        image:"https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NzQ0NjUxMDk1NDE4NDk4/cristiano-ronaldo-festeja.jpg",
        position: "Delantero",
    },
    {
        id: 3,
        name: "Neymar Jr",
        team: "PSG",
        country: "Brasil",
        age: 28,
        image:"https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NzQ0NjUxMDk1NDE4NDk4/cristiano-ronaldo-festeja.jpg",
        position: "Delantero",
    },
    {
        id: 4,
        name: "Kylian Mbappé",
        team: "PSG",
        country: "Francia",
        age: 21,
        image:"https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NzQ0NjUxMDk1NDE4NDk4/cristiano-ronaldo-festeja.jpg",
        position: "Delantero",
    },
    {
        id: 5,
        name: "Sergio Ramos",
        team: "Real Madrid",
        country: "España",
        age: 34,
        image:"https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NzQ0NjUxMDk1NDE4NDk4/cristiano-ronaldo-festeja.jpg",
        position: "Defensa",
    },
    {
        id: 6,
        name: "Robert Lewandowski",
        team: "Bayern Munich",
        country: "Polonia",
        age: 32,
        image:"https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NzQ0NjUxMDk1NDE4NDk4/cristiano-ronaldo-festeja.jpg",
        position: "Delantero",
    },
    {
        id: 7,
        name: "Kevin De Bruyne",
        team: "Manchester City",
        country: "Belgica",
        age: 29,
        image:"https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NzQ0NjUxMDk1NDE4NDk4/cristiano-ronaldo-festeja.jpg",
        position: "Mediocampista",
    }
]
